FROM aursu/rpmbuild:7-build

USER root
RUN yum -y install \
        expat-devel \
        libcurl-devel \
        libxml2-devel \
        lua-devel \
        pcre-devel \
        perl-generators \
        yajl-devel \
    && yum clean all && rm -rf /var/cache/yum

RUN yum -y --enablerepo custom  --enablerepo bintray-custom install \
        httpd-devel \
    && yum clean all && rm -rf /var/cache/yum
